### ISSUE TITLE
Error on Launch = 14" MBP

### ISSUE THREAD

**Issue by itsthenat** [tlkh/asitop#10]
asitop

[1/3] Loading ASITOP

[2/3] Starting powermetrics process

[3/3] Waiting for first reading...

Password:
Traceback (most recent call last):
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/utils.py", line 21, in parse_powermetrics
    bandwidth_metrics = parse_bandwidth_metrics(powermetrics_parse)
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/parsers.py", line 41, in parse_bandwidth_metrics
    bandwidth_metrics_dict["VENC1 DCS RD"]
KeyError: 'VENC1 DCS RD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nat/Library/Python/3.8/bin/asitop", line 8, in <module>
    sys.exit(main())
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/asitop.py", line 118, in main
    ready = get_reading()
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/asitop.py", line 115, in get_reading
    ready = parse_powermetrics(timecode=timecode)
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/utils.py", line 31, in parse_powermetrics
    bandwidth_metrics = parse_bandwidth_metrics(powermetrics_parse)
  File "/Users/nat/Library/Python/3.8/lib/python/site-packages/asitop/parsers.py", line 41, in parse_bandwidth_metrics
    bandwidth_metrics_dict["VENC1 DCS RD"]
KeyError: 'VENC1 DCS RD'

**Comment by cheng-chi** [comment]
I'm having the same issue on MBP 14 with M1 Pro, python3.9

**Comment by tlkh** [comment]
Okay, I think the issue is different labelling for the video encoder on M1 Pro (sorry, I don’t have one to test on) 

I’ll try to fix it later today.

**Comment by tlkh** [comment]
Can you try to update to 0.0.18 and see if it works?

```shell
pip install asitop --upgrade
```

**Comment by itsthenat** [comment]
Yay it works perfectly now, thanks so much for this tool it's awesome!!

**Comment by cheng-chi** [comment]
It works for me as well! Thanks!
