### ISSUE TITLE
KeyError: 'machdep.cpu.brand_string' on M1 Macbook Air (2020)

### ISSUE THREAD

**Issue by clstaudt** [tlkh/asitop#63]
```
➤ asitop

ASITOP - Performance monitoring CLI tool for Apple Silicon
You can update ASITOP by running `pip install asitop --upgrade`
Get help at `https://github.com/tlkh/asitop`
P.S. You are recommended to run ASITOP with `sudo asitop`


[1/3] Loading ASITOP


/bin/sh: sysctl: command not found
/bin/sh: sysctl: command not found
Traceback (most recent call last):
  File "/opt/homebrew/bin/asitop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/asitop/asitop.py", line 36, in main
    soc_info_dict = get_soc_info()
                    ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/asitop/utils.py", line 140, in get_soc_info
    "name": cpu_info_dict["machdep.cpu.brand_string"],
            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'machdep.cpu.brand_string'
```

**Comment by conornash** [comment]
Instead of running `asitop`, try running `sudo asitop`. This fixed the issue for me.

**Comment by hh23485** [comment]
The same to me, and I am already in root user

**Comment by Vlor999** [comment]
Hi everyone, since this project seems to be unmaintained and has accumulating bugs with recent macOS updates, I've created an actively maintained fork called mxtop. It includes pending community fixes and is fully working on the latest Apple Silicon chips.
You can install it right now using: pip install mxtop The new repository is here: https://github.com/Vlor999/mxtop
Feel free to open issues or PRs there!
